
spring:
  # mysql数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.43.182.254:3306/olms?serverTimezone=GMT%2B8
    username: lsh
    password: wL2002s26H.q
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    database: 0
    host: 101.43.182.254
    port: 6379
    password: wL2002s26H.q
  servlet:
    multipart:
      max-file-size: 4MB

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰映射
    map-underscore-to-camel-case: true
  type-aliases-package: com.cuit9622.olms.entity

  global-config:
    db-config:
      # 雪花算法
      id-type: auto
      # 指定表的前缀
      table-prefix: sys_
# 文件上传的保存路径
filePath: C:/olms_files/img/