name: 'Coding auto push'

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

env:
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run
        env:
          CODING_PRIVATE: ${{ secrets.CODING_PRIVATE }}
        run: bash ./.github/main.sh
